Repository DeVinci-FabLab/statuts, pull requests merged in 2024-04, with the labels that each got.

#19 Comités
  Statuts.md
Labels: ajout, mise à jour

#24 ajout de la définition du comité de soutien
  Statuts.md
Labels: ajout

#8 Clarification du statut de Membre Alumni et modification des contraintes
  Statuts.md
Labels: refonte, mise à jour

#23 22 maj comité de contrôle
  Statuts.md
Labels: ajout, mise à jour

#26 Ajout de l'article 1.7 : Règlement Intérieur
  Statuts.md
Labels: ajout

#29 L'AG de rentrée est maintenant une AGO
  Statuts.md
Labels: mise à jour

#30 Ajout d'un comité de gestion
  Statuts.md
Labels: réécriture, mise à jour

#7 Clarification du statut de Membre d'Honneur et du processus de vote
  Statuts.md
Labels: refonte, mise à jour

#33 Suppression du vote des MH avant l'AG
  Statuts.md
Labels: suppression
